[package]
name = "rcontrol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasts = "0.8"
stick = "0.12"
device_query = "0.1.0"
enigo = "0.1.0"
